server:
  #  设置基地址为 http://localhost:8080/actionmall
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mechmall?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: yh020316
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 120MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis:
  type-aliases-package: com.mall.mechmall.domain
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: mechmall_secret_key
  expiration: 86400000 # JWT过期时间，单位毫秒（这里设置为1天）
  header: Authorization
  prefix: Bearer

alipay:
  appId: 9021000138689747
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC35fH3x8MNk4IPkvaXZbEOyVZeFOzf/URtq519spwqHVA5Ey8BtuYzerahRlETpEpUR07U8uyDfTRZenxrcucLxOC0mx1TFB0i2mwIrfoQ6rEcrY+7aiRgGSGaN82rHebXyoD1klYhVJtl3A6sP0aAc1T9TYJEHYVFaqwx0Oa4IGYZM35m3yYWS0mpMD3+FQsomN0f7eg+YWfJkQp4jN9qDrKXnlRQIRjLoQY9u2f9vmvRzzDxw/a6a9TyfoU+q1YwDjgptGcJB+Y/NEOhaN/1WH2jAxP1Ngge9y5xubSDT1RTb9RDK3Ur4LCwMxLTZLxDSmK6wEsbl89AaXAOFoVrAgMBAAECggEBAKQoabTr51xJHsLUR7eiGUm/xI87UrAoH1te5Ll+JRUbEa/BRibbo+a0Vi7k3B8Sex98gAxrxWEi9QYi5snryf+hgYz3Ilg1DkU8gU/GLgHH3s5gyHteJpZ6GJrX0Yo8qQJcTH3qYWRjaEynAZoU6dRkH6v18qDnUT5EGO5nMm2NSNNJcIGOM77h0mT0MnNchh7Bmx/5CSFN+dAgPvcIZZm7oi3L8wY75e9TrP1Vc4Ea3U5eaFTh/MqEvr1TaPVLzCtbORFekBeijMBC+lYifCaiTuHqRg/aVh2s2T5it7y2gFZ5KPki0qZWpo0K3KU24HItRhtoJEhY0PYfTTj8TsECgYEA8QKimKUTtXldvmkZj+VNOOCnJC+3QJVoks9FyxzqWTCkh6M07EpwJOBdFW/WgocpNKVF98ySpy1kth08YyrgJIW5TbU/PpRrFm4oqtyNhhnjwdEIhLh1VAfTMFxOJkqCAaVxRNk4GeNX26itx3jkiuPpcLKtZpqpPUjQoINQAnsCgYEAw1X4zxgaKm1hjX8FPYGfkLKqU1BXzVOTUr/67VbBDoQdcNlyX5WsI3ib+Vd2W2IO5jbNnaMRo6dhskrdaC9pRaQIdTru9a9sDbk5VwmtfXjqw1iIfzZPRWNq2iSqf4wrxuZZgwChw54fLRL/NXTCI7KVaVVnaRMHwJNKfBDYzdECgYBq9Jxr2XZxpravdbzeWwh2IVyLdpGAm82YuVtj1CU8B5Y8i3VFF5PFCbzFcqhjrM/giSgP3D2I62AyYa8W40QtcRrXHYQ/pWYQwjpR+SblSEAHF1kMbT/EVuSmJZCY9Z/UUzN9NljrRDUNSkI0r7Xc3WAPn3vMeP56MAJF+YBcWQKBgBD1k+aXFx575K5eStwuNuZfPL6DCTyAdxgGJwkYMSbLfargljeKTSm/PPuHBnWkq9p9A5keIVfuHmNWcKatBxzOwxU6iqi2FFGUtU/DPVbZerh/JUq2Mme52/sYl9z/FIXuVfMzyNetENPfBF1lx71Fsgc1LQdIabHkl+DxrYEhAoGAHVucM79NgO6DqyidvTNizpj8qwssZgwu3o+udaa94FYYQdfSq5a3UhjiekDXCZwsIVCEYlJbmmy2bR5TsigZjFkbYgyToa2OBuzYdXrUZb98F7tGVXUIe5fsyauARA7d6M+tJm+yMQ3ouT+qXMQwUM68xjjiABKYrJ7xmsFfL14=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA26hVgOfDv6v8TDlIq1NMrwjALhik6ItpiO8/5g7IGK90kkMNNDlR1+Tdt/bPpgSdBxwq0vnZyhqnoZ9SP/erjl1KklBiKWFVl3eAtYcQjxAnVyqdnXEWrf1/znEVsCq3WbBsfZI/acHCtUf1aUOnXmzV+hnkoXoZu6Euf5qzmU02jEtGbGA7hN/3VUa8Ws1B991fbT3yeoYHVCHGV2WS4b7k0AOno3sVvh7bKp9uYElhYR1zmETmdjypivwbhMKENhy/sESwsyVynWU6Xts+AMQSTUZKt88uZE8gvXyrHc/EfERjonofEvyvXGWCqx6AGsAYFyalz9FHGTQvYSbiqwIDAQAB
  notifyUrl: http://pmikd3.natappfree.cc/alipay/notify
